# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pederson's Website
email: jayromjavier@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pederson's website description
baseurl: "/Pederson" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: jhepong24
github_username:  jhepong

# Build settings
markdown: kramdown
